services:
  openra:
    image: openra:${SERVICE_VERSION_ABSOLUTE}
    container_name: openra
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - Name=JaneAndGraham
      - ListenPort=${OPENRA_API_PORT}
      - Mod=d2k
      - Map=
      - AdvertiseOnline=False
      - Password=${OPENRA_TOKEN}
      - RecordReplays=False
      - RequireAuthentication=False
      - ProfileIDBlacklist=
      - ProfileIDWhitelist=
      - EnableSingleplayer=False
      - EnableSyncReports=False
      - EnableGeoIP=True
      - EnableLintChecks=True
      - ShareAnonymizedIPs=True
      - FloodLimitJoinCooldown=5000
      - SupportDir=
    volumes:
      - ${SERVICE_DATA_DIR}:/asystem/mnt:rw
    ports:
      - ${OPENRA_API_PORT}:${OPENRA_API_PORT}
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 1m
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 512M
