################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Internet Telemetry
  entities:
    - entity: sensor.network_internet_ping
      name: Ping
      icon: mdi:cloud-refresh
    - entity: sensor.network_internet_upload
      name: Upload
      icon: mdi:cloud-upload
    - entity: sensor.network_internet_download
      name: Download
      icon: mdi:cloud-download
    - entity: sensor.network_certificate_expiry
      name: Certifcate Expiry
      icon: mdi:cloud-lock
################################################################################
- type: entities
  title: WiFI Link Quality
  entities:
    - entity: sensor.deck_wifi_access_point_experience
      name: Deck Access Point
    - entity: sensor.hallway_wifi_access_point_experience
      name: Hallway Access Point
################################################################################
- type: entities
  title: Zigbee Link Quality
  entities:
    - entity: sensor.template_driveway_repeater_linkquality_percentage
      name: Driveway Repeater
    - entity: sensor.template_landing_repeater_linkquality_percentage
      name: Landing Repeater
    - entity: sensor.template_garden_repeater_linkquality_percentage
      name: Garden Repeater
    - entity: sensor.template_kitchen_fan_outlet_linkquality_percentage
      name: Kitchen Fan Outlet
    - entity: sensor.template_deck_fans_outlet_linkquality_percentage
      name: Deck Fans Outlet
    - entity: sensor.template_edwin_wardrobe_outlet_linkquality_percentage
      name: Edwin Wardrobe Outlet
################################################################################
- type: entities
  title: Radio Link Quality
  entities:
    - entity: sensor.template_weatherstation_coms_signal_quality_percentage
      name: Davis Console
################################################################################
- type: entities
  title: Service Availability
  entities:
    - entity: binary_sensor.service_homeassistant_availability
      name: Home Assistant
    - entity: binary_sensor.service_plex_availability
      name: Plex
    - entity: binary_sensor.service_grafana_availability
      name: Grafana
    - entity: binary_sensor.service_wrangle_availability
      name: Wrangle
    - entity: binary_sensor.service_internet_availability
      name: Internet
    - entity: binary_sensor.service_unifi_availability
      name: UniFi
    - entity: binary_sensor.service_zigbee2mqtt_availability
      name: Zigbee2Mqtt
    - entity: binary_sensor.service_weewx_availability
      name: Weewx
    - entity: binary_sensor.service_digitemp_availability
      name: Digitemp
    - entity: binary_sensor.service_nginx_availability
      name: Nginx
    - entity: binary_sensor.service_influxdb_availability
      name: Influxdb
    - entity: binary_sensor.service_mariadb_availability
      name: Mariadb
    - entity: binary_sensor.service_postgres_availability
      name: Postgres
    - entity: binary_sensor.service_letsencrypt_availability
      name: Letsencrypt
    - entity: binary_sensor.service_unifipoller_availability
      name: Unifipoller
    - entity: binary_sensor.service_monitor_availability
      name: Monitor
################################################################################
- type: entities
  title: Host Availability
  entities:
    - entity: binary_sensor.host_eva_availability
      name: Mac Mini Eva
    - entity: binary_sensor.host_meg_availability
      name: Mac Mini Meg
    - entity: binary_sensor.host_lia_availability
      name: Raspberry Pi Lia
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Device Maintenance
  show_header_toggle: false
  entities:
    - entity: button.google_assistant_synchronize_devices
      name: Google Device Syncronise
################################################################################
- type: entities
  title: Device Conditions Rack
  entities:
    - entity: sensor.template_utility_temperature_proxy
      name: Rack Ambient
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_rack_top_temperature
      name: Rack Top
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_rack_bottom_temperature
      name: Rack Bottom
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_host_eva_temperature
      name: Mac Mini Eva
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_host_meg_temperature
      name: Mac Mini Meg
      icon: mdi:thermometer
################################################################################
- type: entities
  title: Device Conditions Ceiling
  entities:
    - entity: sensor.template_deck_festoons_plug_temperature_proxy
      name: Ceiling Ambient
      icon: mdi:thermometer
################################################################################
- type: entities
  title: Device Conditions Wardrobe
  entities:
    - entity: sensor.template_wardrobe_temperature_proxy
      name: Wardobe Ambient
      icon: mdi:thermometer
    - entity: sensor.compensation_sensor_host_lia_temperature
      name: Raspberry Pi Lia
      icon: mdi:thermometer
################################################################################
- type: entities
  title: Device Batteries
  entities:
    - entity: sensor.back_door_lock_battery
      name: Yale Back Door Lock
    - entity: sensor.front_door_lock_battery
      name: Yale Front Door Lock
    - entity: sensor.template_back_door_sensor_battery_last
      name: Sonoff Back Door Sensor
    - entity: sensor.template_front_door_sensor_battery_last
      name: Sonoff Front Door Sensor
    - entity: sensor.template_weatherstation_console_battery_percent_int
      name: Davis Console
    - entity: sensor.office_pantry_battery
      name: Netatmo Pantry
    - entity: sensor.office_lounge_battery
      name: Netatmo Lounge
    - entity: sensor.office_dining_battery
      name: Netatmo Dining
    - entity: sensor.office_basement_battery
      name: Netatmo Basement
    - entity: sensor.parents_move_battery
      name: Sonos Parents
    - entity: sensor.kitchen_move_battery
      name: Sonos Kitchen
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Power Plugs
  show_header_toggle: false
  entities:
    - entity: switch.lounge_tv_plug
      name: Lounge TV
      icon: mdi:television
    - entity: switch.lounge_sub_plug
      name: Lounge Sub
      icon: mdi:speaker
    - entity: switch.study_outlet_plug
      name: Study Outlet
      icon: mdi:power-plug-outline
    - entity: switch.kitchen_dish_washer_plug
      name: Dish Washer
      icon: mdi:dishwasher
    - entity: switch.laundry_clothes_dryer_plug
      name: Clothes Dryer
      icon: mdi:tumble-dryer
    - entity: switch.laundry_washing_machine_plug
      name: Washing Machine
      icon: mdi:washing-machine
    - entity: switch.kitchen_fridge_plug
      name: Kitchen Fridge
      icon: mdi:fridge-outline
    - entity: switch.deck_freezer_plug
      name: Deck Freezer
      icon: mdi:fridge-top
    - entity: switch.study_battery_charger_plug
      name: Battery Charger
      icon: mdi:battery-charging-30
    - entity: switch.laundry_vacuum_charger_plug
      name: Vacuum Charger
      icon: mdi:battery-charging-30
    - entity: switch.ada_tablet_plug
      name: Ada Tablet
      icon: mdi:tablet
    - entity: switch.server_eva_plug
      name: Server Eva
      icon: mdi:server
    - entity: switch.server_meg_plug
      name: Server Meg
      icon: mdi:server
    - entity: switch.server_lia_plug
      name: Server Lia
      icon: mdi:server
    - entity: switch.rack_outlet_plug
      name: Server Rack
      icon: mdi:server
    - entity: switch.ceiling_network_switch_plug
      name: Network Switch
      icon: mdi:server-network
    - entity: switch.rack_internet_modem_plug
      name: Internet Modem
      icon: mdi:router-wireless
    - entity: fan.rack_fans_plug
      name: Rack Fans
      icon: mdi:server-remove
    - entity: switch.deck_fans_outlet
      name: Deck Fans Outlet
      icon: mdi:power-plug-outline
    - entity: switch.kitchen_fan_outlet
      name: Kitchen Fan Outlet
      icon: mdi:power-plug-outline
    - entity: switch.edwin_wardrobe_outlet
      name: Edwin Wardobe Outlet
      icon: mdi:power-plug-outline
################################################################################
- type: entities
  title: Reset Adaptive Lighting
  show_header_toggle: false
  entities:
    - entity: input_boolean.lighting_reset_adaptive_lighting_all
      name: All Lights
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_ada_lamp
      name: Ada Lamp
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_edwin_lamp
      name: Edwin Lamp
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_edwin_night_light
      name: Edwin Night Light
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_hallway_main
      name: Hallway Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_hallway_sconces
      name: Hallway Sconces
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_dining_main
      name: Dining Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_lounge_main
      name: Lounge Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_lounge_lamp
      name: Lounge Lamp
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_parents_main
      name: Parents Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_parents_jane_bedside
      name: Jane Bedside
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_parents_graham_bedside
      name: Graham Bedside
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_study_lamp
      name: Study Lamp
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_kitchen_main
      name: Kitchen Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_laundry_main
      name: Laundry Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_pantry_main
      name: Pantry Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_office_main
      name: Office Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_bathroom_main
      name: Bathroom Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_bathroom_sconces
      name: Bathroom Sconces
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_ensuite_main
      name: Ensuite Main
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_ensuite_sconces
      name: Ensuite Sconces
      icon: mdi:lightbulb-group
    - entity: input_boolean.lighting_reset_adaptive_lighting_wardrobe_main
      name: Wardrobe Main
      icon: mdi:lightbulb-group
################################################################################
