# https://github.com/vernemq/vernemq/releases
version: '3.7'
services:
  vernemq:
    container_name: vernemq
    image: vernemq/vernemq:1.12.3-alpine
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on

    # TODO: Get permission denied?
    #    volumes:
    #      - ${SERVICE_DATA_DIR}:/var/lib/vernemq

    ports:
      - ${VERNEMQ_PORT}:${VERNEMQ_PORT}
    deploy:
      resources:
        limits:
          memory: 5G
