# https://registry.hub.docker.com/r/linuxserver/ddclient/tags
version: '3.7'
services:
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient:v3.9.1-ls40
    init: true
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=501
      - PGID=20
    volumes:
      - ${SERVICE_DATA_DIR}:/config
    deploy:
      resources:
        limits:
          memory: 5G