#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
#######################################################################################
fan:
  - platform: group
    name: Deck Fan
    unique_id: deck_fan
    entities:
      - fan.deck_east_fan
      - fan.deck_west_fan
#######################################################################################
tplink:
  discovery: false
  switch:
    - host: 10.0.4.70
    - host: 10.0.4.71
    - host: 10.0.4.72
    - host: 10.0.4.73
    - host: 10.0.4.74
    - host: 10.0.4.75
    - host: 10.0.4.76
    - host: 10.0.4.77
    - host: 10.0.4.78
    - host: 10.0.4.79
    - host: 10.0.4.80
    - host: 10.0.4.81
    - host: 10.0.4.82
    - host: 10.0.4.83
    - host: 10.0.4.84
    - host: 10.0.4.85
    - host: 10.0.4.86
    - host: 10.0.4.87
    - host: 10.0.4.88
    - host: 10.0.4.89
    - host: 10.0.4.90
    - host: 10.0.4.91
    - host: 10.0.4.92
#######################################################################################
