services:
  sabnzbd:
    image: sabnzbd:${SERVICE_VERSION_ABSOLUTE}
    container_name: sabnzbd
    init: false
    restart: ${SERVICE_RESTART}
    environment:
      - TZ=Australia/Perth
      - PUID=0
      - PGID=0
      - SABNZBD_SERVICE_PROD
      - SABNZBD_HTTP_PORT
      - SABNZBD_API_KEY
      - SABNZBD_NZB_KEY
      - SABNZBD_SHARE_DIR
    volumes:
      - ${SERVICE_DATA_DIR}:/config
      - ${SABNZBD_SHARE_DIR}/enqueued:/downloads/enqueued
      - ${SABNZBD_SHARE_DIR}/finished:/downloads/finished
      - ${SABNZBD_SHARE_DIR}/staging:/downloads/staging
    ports:
      - ${SABNZBD_HTTP_PORT}:8080
    healthcheck:
      test: /asystem/etc/checkhealthy.sh
      interval: 2m
      timeout: 30s
      retries: 3
      start_period: 60s
      start_interval: 10s
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    deploy:
      resources:
        limits:
          memory: 2G