#######################################################################################
# WARNING: This file is written to by the build process, any manual edits will be lost!
################################################################################
- type: entities
  title: Internet
  entities:
    - entity: sensor.network_internet_uptime
      name: Up
      icon: mdi:cloud-check
    - entity: sensor.network_internet_ping
      name: Ping
      icon: mdi:cloud-refresh
    - entity: sensor.network_internet_upload
      name: Upload
      icon: mdi:cloud-upload
    - entity: sensor.network_internet_download
      name: Download
      icon: mdi:cloud-download
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Soft Resets
  show_header_toggle: false
  entities:
    - entity: switch.various_adhoc_outlet
      name: Adhoc Outlet
      icon: mdi:power-plug-outline
    - entity: switch.study_outlet
      name: Study Outlet
      icon: mdi:power-plug-outline
    - entity: switch.office_outlet
      name: Office Outlet
      icon: mdi:power-plug-outline
    - entity: switch.kitchen_dish_washer
      name: Dish Washer
      icon: mdi:dishwasher
    - entity: switch.laundry_clothes_dryer
      name: Clothes Dryer
      icon: mdi:tumble-dryer
    - entity: switch.laundry_washing_machine
      name: Washing Machine
      icon: mdi:washing-machine
    - entity: switch.kitchen_coffee_machine
      name: Coffee Machine
      icon: mdi:coffee-maker
    - entity: switch.kitchen_fridge
      name: Kitchen Fridge
      icon: mdi:fridge-outline
    - entity: switch.deck_freezer
      name: Deck Freezer
      icon: mdi:fridge-top
    - entity: switch.bathroom_rails
      name: Bathroom Rails
      icon: mdi:radiator
    - entity: switch.study_battery_charger
      name: Battery Charger
      icon: mdi:battery-charging-30
    - entity: switch.laundry_vacuum_charger
      name: Vacuum Charger
      icon: mdi:battery-charging-30
################################################################################
- type: entities
  title: Hard Resets
  show_header_toggle: false
  entities:
    - entity: switch.lounge_tv
      name: Lounge TV
      icon: mdi:television
    - entity: switch.rack_outlet
      name: Server Rack
      icon: mdi:server
    - entity: switch.roof_network_switch
      name: Network Switch
      icon: mdi:server-network
    - entity: switch.rack_modem
      name: Internet Modem
      icon: mdi:router-wireless
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Netatmo Battery
  entities:
    - entity: sensor.netatmo_bertram_2_office_pantry_battery_percent
      name: Pantry
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_lounge_battery_percent
      name: Lounge
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_dining_battery_percent
      name: Dining
      icon: mdi:battery-30
    - entity: sensor.netatmo_bertram_2_office_basement_battery_percent
      name: Basement
      icon: mdi:battery-30
################################################################################
- type: entities
  title: Sonos Battery
  entities:
    - entity: sensor.parents_speaker_battery
      name: Parents
      icon: mdi:battery-30
    - entity: sensor.kitchen_home_battery
      name: Kitchen
      icon: mdi:battery-30
################################################################################
- type: entities
  title: Davis Battery
  entities:
    - entity: sensor.weatherstation_console_battery_voltage
      name: Console Voltage
      icon: mdi:battery-30
################################################################################
- type: custom:layout-break
################################################################################
- type: entities
  title: Davis Telemetry
  entities:
    - entity: sensor.weatherstation_sample_period
      name: Sample Period
      icon: mdi:clipboard-clock-outline
    - entity: sensor.weatherstation_coms_signal_quality
      name: Coms Signal Quality
      icon: mdi:signal
################################################################################
